<html>
<head>
    <script>
        let promise = new Promise(function(resolve, reject) {
            // after 1 second signal that the job is finished with an error
            setTimeout(() => reject(new Error("Whoops!")), 1000);
        });

        promise.catch(error => {
            console.log('error: ' + error.message);
        }).finally(() => {
            console.log("Promise ready");
        });
    </script>
</head>
</html>